### ISSUE TITLE
Voice support

### ISSUE THREAD

**Issue by MCausc78** [MCausc78/stoat.py#4]
Recently Zoma said that voice on backend  side is almost done. So I would want to implement it in library.
https://github.com/revoltchat/backend/pull/318

I have 2 options:
1. Implement only new voice. (Livekit)
2. Implement both. This is going to be hard task as Vortex is going to shut down soon. However, this is needed for older instances that do not support Livekit.

**Comment by thisismisha** [comment]
насрал

**Comment by thisismisha** [comment]
f3f5
